### ISSUE TITLE
Add Microsoft Edge support

### ISSUE THREAD

**Issue by happycappie** [krtek4/MultiPass#102]
Would you consider adding Microsoft Edge support?

**Comment by krtek4** [comment]
The extension should work in Edge as is : https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026#:~:text=Add%20an%20extension%20to%20Microsoft%20Edge%20from%20the%20Chrome%20Web,then%20select%20Allow%20to%20confirm

**Comment by conradpronto** [comment]
Confirmed, thank you!
