### ISSUE TITLE
Extension get removed after working with Chromedriver

### ISSUE THREAD

**Issue by iRaghothaman** [krtek4/MultiPass#104]
On performing any automated test with Chromedriver session, once its completed. on initiating new session with chrome the extension is removed.
Had to manually add the extension again, but although the saved credentials are cached.

Browser : Google Chrome 
Version : 124.0.+
Operating system : Mac
Version : Sonoma 14.4

**Comment by krtek4** [comment]
I am not familiar with ChromeDriver at all, but after a quick search, it seems that extensions need to be added specifically to it (see https://stackoverflow.com/questions/16531479/extensions-installed-on-chrome-browser-missing-when-chrome-browser-instance-is-o for example).

Anyhow, I don't think this is an issue with the extension itself but rather with ChromeDriver.

Closing this for now, if you have any suspicion that it's Multipass itself that removes itself, please reopen with more context.
