### ISSUE TITLE
Add the ability to import credentials from command line

### ISSUE THREAD

**Issue by Silvanoc** [krtek4/MultiPass#19]
It would be great, if the credentials could be imported using some command line tool, this would ease automatic installations a lot.

**Comment by krtek4** [comment]
Hi,

I quickly looked if this is possible and found no easy solution to implement that.

Are you aware of any extension already doing this ?

Even better, are you willing to take some time to research the feasibility of this ?

I don't have much time now to work on this extension, so any help might speed up things a lot !

**Comment by krtek4** [comment]
Hi @Silvanoc,

I did some research and as far as I found this is not possible sadly.

Feel free to reopen this issue if you have any idea on how this could be achieved.

Best,
