### ISSUE TITLE
When browser was opened, it couldn't pass BASIC authetication automatically

### ISSUE THREAD

**Issue by tkm-kj** [krtek4/MultiPass#21]
Hi:)
Thank you for nice product!

There is a problem about this extension.
When I start the computer(OS: windows 7) and startup program(open the site set BASIC authentication with chrome) is running, the extension can't work and pass authentication automatically.

Do you have any solution?

**Comment by krtek4** [comment]
Hi there,

I am not sure I understand completely the issue at hand.

Can you eventually provide an URL of the website where you are trying to use the extension and the credentials so I can test for myself and see if there is an issue ?

Otherwise, at least please describe each step you take :) Did you correctly enter the URL and credentials for the website in the extension ?

Cheers,

**Comment by tkm-kj** [comment]
OK, I'll show you steps:)

step1: Add URL and BASIC authentication info
![1](https://cloud.githubusercontent.com/assets/3395349/10020152/499f34dc-617c-11e5-88f3-cac0e79d73bb.jpg)

step2: Copy chrome shortcut to startup directory
![2](https://cloud.githubusercontent.com/assets/3395349/10020280/ff219e26-617c-11e5-8347-9eeee93a25af.jpg)
In my case, startup directory is `C:\Users\kj\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.

step3: Edit property
![3](https://cloud.githubusercontent.com/assets/3395349/10020442/d47ae294-617d-11e5-9b10-e62027a21492.jpg)
Please input `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" http://basic-sample.herokuapp.com` in the `Target:` line's form.

step4: Restart windows

After starting windows, chrome starts automatically and open http:basic-sample.herokuapp.com.
But, can't pass BASIC authentication.
![4](https://cloud.githubusercontent.com/assets/3395349/10020759/9842e86a-617f-11e5-97dd-90f59564eea4.jpg)

By the way, When I reloaded browser here, extension worked and passed authentication.

**Comment by krtek4** [comment]
The way you're describing this, it seems this is more of an issue with Chrome not using extension when the URL come from the startup command.

I'll try to have a look, but since it is working when you are entering the URL in the address bar, I don't think there is much I can do.
