### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by krtek4** [krtek4/MultiPass#28]
Now that Firefox as a pretty good WebExtension API, porting should be doable.
- [x] build a XPI
- [x] Add needed data in the manifest ("application" key)
- [x] Separate specific manifests info
- [x] FF does not support `sync` storage, fallback to `local`
- [x] [webRequest.onAuthRequired is not supported ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired), find a workaround
- [x] Sync between the "popin" and the "option pane" is broken
- [x] Adding a credential via the popin does not work

*update*: Check the issues again now that a bug was fixed

**Comment by krtek4** [comment]
Fixed the popin issue by removing a call to a deprecated API.

We now only need to find a workaround to send the authentication ^^

**Comment by krtek4** [comment]
Instead of sending credentials only when they are asked, we always send them as soon as the URL matches... dirty hack :/

**Comment by Francewhoa** [comment]
Vladimir Chebotarev ported a similar add-on to Firefox at https://addons.mozilla.org/en-US/firefox/addon/multipass-disarmed/
