### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by krtek4** [krtek4/MultiPass#40]
The addons has been rejected on the Mozilla Add-ons website because it uses the Google Analytics script.

> 1) A custom CSP for GA is not allowed, as it allowed remote script injection. Please see https://blog.mozilla.org/addons/2016/05/31/using-google-analytics-in-extensions/ for a way to do this properly.

As I don't use Firefox, I don't have nor the time, nor the motivation to fix this. If anyone wants to do a PR working for Chrome, Opera and Firefox to fix this issue, feel free.

The addons also needs a Privacy Policy since we send information to GA, as stated in the link above.

Also, the sources must be attached as a zip file next time the addon is submitted alongside build instructions.

**Comment by krtek4** [comment]
As I had to make changes to the analytics anyway, I disabled them on Firefox altogether and resubmitted the addon.

Someone should still tackle adding GA correctly.

**Comment by blahjig** [comment]
Why would you want google analytic inside the extension? I certainly dont want it present.

**Comment by krtek4** [comment]
That's a fair point, and I saw your other issues about a config switch ( #44 ).

I personally use it for multiple reasons :

* determining what errors / exceptions happen and try to find a way to correct them
* determining what feature people use to know what to improve
* bragging about the number of users ;)

I already disabled most of the tracking in the last release anyway because there were too many hits on GA. Only a handful things are tracked now :

* opening of the option panel
* opening of the popin
* adding a credential
* various kind of errors : form errors, import errors, invalid credentials, multiple credentials

I think we can continue this discussion on the other issues. Let's keep this one about Firefox only.

**Comment by krtek4** [comment]
The addon was accepted for Firefox, closing this. I will open another issue about the analytics.

See : https://addons.mozilla.org/en-US/firefox/addon/multipass/

**Comment by bastien30** [comment]
Hi,
The addon is marked as experimental on AMO, and there is only the 0.7.0 version.
Do you plan to release following versions on it ?
We could then benefit of automatic update.
Thanks.

**Comment by krtek4** [comment]
Hi @bastien30,

I tried to and honestly it is a PITA. Each accepted release required a number of e-mail back and forth and a lot of lost time.

For example, the 0.7.4 release was rejected for the following reasons:

```

1) We don't allow add-ons to use remote scripts because they can create serious security vulnerabilities. We also need to review all add-on code, and this makes it much more difficult. Please insert those scripts locally from your add-on code.
eg:
js/extension.js#L201
js/option.js#L303
js/popin.js#L144

2) We do not allow the Google Analytics script to be included in the extension, you need to use a content iframe to include GA.
```

If you look at the code, you can clearly see not even 10 lines above the three mentioned occurences that there is an exception for Firefox disabling GA entirely.

This means the reviewer didn't even take the time to read the code correctly, nor the history of the addon as this was already discussed multiple times in the previous releases.

Also, the reviewer had full access to the changes since the last release but didn't bother to look at them. Otherwise he would have see that nothing related to GA was changed since the last accepted release.

Anyhow, as I am not a Firefox user, I don't have such time to lose. I am however more than willing to appoint an official maintainer for the FF version. Let me know if you are interested.

PS: as a comparison, uploading the new version for Chrome and Opera takes roughly 2 minutes each. Even filling the initial submission form for Firefox takes longer than that :(

**Comment by bastien30** [comment]
Hi @krtek4,

Thanks for this detailed answer.

What about replacing the three Google Analytics URL by a local analytics.js file that just contains, for example, a simple "return" ? If analytic is not used at all, this should not be a problem ?

But maybe you've already thinking about this and that it's not feasible...

> I am however more than willing to appoint an official maintainer for the FF version. Let me know if you are interested.

Thanks, I would do it if I could, unfortunately, I think I don't have the necessary skills...

**Comment by krtek4** [comment]
Hi,

GA can be used by Chrome and Opera. It was disabled on Firefox due to their external script policy.

What bothers me is that I already spent time doing that *only* to pass the Firefox approval process, discussed that at length with previous reviewers, and now the addon get rejected due to false pretense that it loads the external GA script.

I could write different scripts for the different browsers, but that would induce  more time spent maintaining the extension and I don't have it right now. And I also don't want to simply disable GA for everyone.

I am sorry I can't be of more help right now. The current version available for Firefox should work well enough until I find some time and motivation or someone steps up :)

**Comment by Francewhoa** [comment]
Vladimir Chebotarev ported a similar add-on to Firefox at https://addons.mozilla.org/en-US/firefox/addon/multipass-disarmed/

**Comment by krtek4** [comment]
Hi @Francewhoa,

Thanks for letting me know, I'll try contacting him to see if we can mutualize our efforts :)
