### ISSUE TITLE
XSS in display of credentials

### ISSUE THREAD

**Issue by blahjig** [krtek4/MultiPass#43]
If you set your url/username/password to html, for example the url \<b\>hello\<\/b\>, the html is rendered.

This also poses a problem if a > is entered preventing a user from correctly editing the entry.

I suppose the issue is only limited to self xss, so its probably not a big risk, other than an annoyance.

**Comment by krtek4** [comment]
Still, it's an issue, thanks for reporting !

I'll try to correct that quickly, expect a new release this week.

**Comment by krtek4** [comment]
Hi @blahjig,

I just released version 0.7.0 on GitHub which should fix the XSS issue according to my tests.

Can you give it a quick test before I upload it to the Chrome and Opera stores ?

Thanks!

**Comment by blahjig** [comment]
Looks good, however there is a similar issue in update_output_credentials when you import html besides "What will be imported?" will render

**Comment by krtek4** [comment]
Good catch, I also added a commit to prevent that. I just tagged version 0.7.0.

If you can confirm me that #44 works for you, I'll release today.

**Comment by blahjig** [comment]
Looks good, I can't see any other places with the same pattern with a quick glance.
