### ISSUE TITLE
Provide information when unchecking "Enable Google Analytics?"

### ISSUE THREAD

**Issue by blahjig** [krtek4/MultiPass#45]
When unchecking "Enable Google Analytics?" the user should be notified that:

* A reload of the extension is required to completely deactivate the included google analytics javascript

And possibly also that:
* Analytics data within the options page and other locations may already have been collected

**Comment by krtek4** [comment]
Thanks for opening this. I'll try to have a look quickly :)

**Comment by krtek4** [comment]
Analytics will be removed, so closing this
