### ISSUE TITLE
Consider asking the user for permission to collect analytics data on first load

### ISSUE THREAD

**Issue by blahjig** [krtek4/MultiPass#46]
When a user first loads the extension, consider asking the user if they are comfortable providing analytics data to the project before any data is collected.

**Comment by krtek4** [comment]
Thanks for opening this. I'll try to have a look quickly :)

**Comment by krtek4** [comment]
I don't have the time to undertake such a development, however, as I said on the mentioned issue, I'd rather disable Analytics completely. Let's wait about what the author of the fork think :)

**Comment by krtek4** [comment]
I'll disable Analytics in the next version, so closing this.
