### ISSUE TITLE
Firefox Addon unsigned and can't be signed

### ISSUE THREAD

**Issue by camjac251** [krtek4/MultiPass#47]
Firefox requires signed addons and MultiPass is being detected as unsigned. I sent it through the AMO on firefox and it had said that it was already a duplicate addon ID.

Validation for it was here https://addons.mozilla.org/en-US/developers/upload/1426ca256c9449a6969c9cb627ba7a83

I'm not sure if firefox gives a new .xpi addon that is signed but the one on the GitHub download page for Firefox won't work.

Is there anything that could be done? There are a few other addons that I've tried in the past that were rejected from the addon site but still could sign their addons and put them on GitHub.

**Comment by krtek4** [comment]
Hi,

I re submitted the addon with Analytics disabled a while ago (see #40 for the reason he was refused the first time), it is currently awaiting validation: https://addons.mozilla.org/en-US/firefox/addon/multipass/

I think you can install it from there even if it is not yet validated.

As I don't use Firefox myself, I wasn't aware that addons now need to be signed, i'll update the documentation accordingly.

Thanks for reporting this, I hope you will be able to install the extension.

**Comment by camjac251** [comment]
It is saying that the addon isn't signed there. Odd though since it's on the addon page
https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Add-on-signing-in-Firefox/ta-p/30262

Would it be possible to sign it and upload to the releases? https://addons.mozilla.org/en-US/developers/addon/submit/distribution is the official way to sign them.

Or maybe if you uploaded a signed addon to the addon page, it would get approved quicker maybe.

**Comment by krtek4** [comment]
Hi @camjac251,

The review process is already underway, but it goes slowly. The signing will be automatically done once it is completed.

In the meantime, I updated the XPI available for the 0.7.0 version with a signed version : https://github.com/krtek4/MultiPass/releases/tag/v0.7.0

You should be able to install it. Let me know.

Cheers,

**Comment by camjac251** [comment]
Thank you. It worked. I tried importing my json export from chrome into firefox but it seemed to fail. I am not too familiar url regex but on Chrome you type the exact url and it will work but on Firefox if you do it will blank all of the field and turn them red. As well as importing into Firefox, it will show you the fields to import but not actually import them after you press the button.

**Comment by krtek4** [comment]
You are right, it seems there is an issue on firefox currently.

I don't have time to look into it right now, but I hope I will have some time to avec a look tomorrow.

In the meantime, can I ask you to open a new issue about this as it is unrelated to the signature issue ?

Thanks

**Comment by krtek4** [comment]
Closing this one as the installation now works.
