### ISSUE TITLE
Issue with GUI using long regex

### ISSUE THREAD

**Issue by jallakim** [krtek4/MultiPass#52]
Hi,

Having long regex-matches seems to "break" the GUI; the width of the "dropdown" window is smaller than the width of the content, causing things to get out of scope, and without any scrollbars. 

Going to the full-page option page, things are still out of scope, but it's possible to at least scroll sideways.

**Comment by jallakim** [comment]
![dump_2017-06-06_11 14 11](https://cloud.githubusercontent.com/assets/359918/26822223/9b1e6ba8-4aa9-11e7-9098-87a1d8e336ac.png)
![dump_2017-06-06_11 14 33](https://cloud.githubusercontent.com/assets/359918/26822225/9b28bb08-4aa9-11e7-92a8-a840603def90.png)

**Comment by krtek4** [comment]
Thanks for the screenshot, I was going to ask one :)

The fix should be pretty straightforward, I plan to limit the width of the column and display an ellipsis to indicate that the regex is actually longer and display it on hover. Would that suits you ?

**Comment by jallakim** [comment]
For showing them; sure. How about editing when you are in the "Popin" window?

**Comment by krtek4** [comment]
Hey, had a pretty eventful week, so the fix is coming rather later than sooner.

I put the ellipsis in place, and when you hover the cell, the full content should be displayed as it is also now put as the title of the cell.

Concerning the edition, I don't have a "good" solution. It is possible to edit it as the input box allows to have longer text, but I agree it is not ideal. Do you have any idea ?

**Comment by krtek4** [comment]
The fix is available in the latest release : https://github.com/krtek4/MultiPass/releases/tag/v0.7.3

I'll publish it after some more test

**Comment by jallakim** [comment]
Hi,

Thanks. Seems to be working so far on my end. I don't think it's necessary to do anything more regarding editing long regexes. Sure, it's a bit cumbersome with a "horisontal scrolling" text input field, but you can just copy/paste stuff, and edit it somewhere else.

**Comment by krtek4** [comment]
Just released on the three addon stores, update should be automatically applied shortly. I am closing this on the meantime :)
