### ISSUE TITLE
MultiPass is not working when used on startup pages

### ISSUE THREAD

**Issue by astbss** [krtek4/MultiPass#54]
If I add pages with HTTP authentication to On Startup asking Chrome to Open a specific page or set of pages in the Settings when I start Chrome. MultiPass do not work.

If I remove this pages from the On Startup in Chrome and just type the URL or use the bookmark the regex kick in and MultiPass is working correctly. 

I am running: Chrome Version 64.0.3282.167 (Official Build) (64-bit) on Linux Gnome Version 3.22.2 on Linux Debian 9.3

**Comment by krtek4** [comment]
I can confirm the same error on my side.

Although I cannot find a good source, it seems the `webRequest` listeners are not called for pages opened on startup (see https://stackoverflow.com/questions/29225317/how-to-get-chrome-webrequest-onbeforerequest-addlistener-to-fire-at-chrome-sta which is a similare issue).

I will try to look into it, but I don't know if something can be done.

In the worst case, simply reloading the page with "Ctrl + R" seems to work just fine.

**Comment by astbss** [comment]
Thank you for the  "Ctrl + R" solution. It is working well. I think this is something that happened last 6 months. But I cannot be 100% sure for the timespan.

Good luck finding a solution

**Comment by krtek4** [comment]
Closing this as it seems there is no solution to fix it :/
