### ISSUE TITLE
Password Show button hide

### ISSUE THREAD

**Issue by amjadalbarail** [krtek4/MultiPass#59]
Hello, 
first of all thank you very much for the effort and sharing this add-on. 
I have a small problem with chrome  , i would like to disable the button of showing the password and let Passwords allways hidden, is this possible : ? 

thanks in advance 
Amjad

**Comment by krtek4** [comment]
Hi,

No it isn't presently and I don't see a way to do this with an option.

If I put an option allowing this, nothing prevents the user to disable the option and have access to the feature again.

The only way is to release a new extension without this feature.

I am closing this as I can't see how to do it. Feel free to reopen if you have a suggestion.

Best,
