### ISSUE TITLE
(Chrome) 'INVALID_CATALOG_DATA' when trying to install

### ISSUE THREAD

**Issue by nottmey** [krtek4/MultiPass#61]
When trying to add the extension to Google Chrome from https://chrome.google.com/webstore/detail/multipass-for-http-basic/enhldmjbphoeibbpdhmjkchohnidgnah I get the the error "INVALID_CATALOG_DATA" and the installation stops.

Version 70.0.3538.110

**Comment by krtek4** [comment]
Hey,

Thanks for the report, one of the language files was wrong.

It should be fixed with the version I just uploaded ( 0.8.4 ).

Let me know if this works for you.

Sorry

**Comment by krtek4** [comment]
Oh god, I forgot to push the "Publish button" in the Dashboard....

Really sorry about that, must have been really tired.

It should be ok now. Apologies for all the troubles.

**Comment by Nekromancer** [comment]
No problem, it happens :)

**Comment by nottmey** [comment]
Works for me now, thank you for the fast response! :)
