### ISSUE TITLE
links

### ISSUE THREAD

**Issue by MonkberryMedium** [krtek4/MultiPass#65]
Is it possible to use this extension with links? In other words. I make a web page that has small previews of cameras and the links that go to the cameras are where the authentication is needed, however, this only works after I click on the link and go to the actual camera. And then if I go back to the main page showing the smaller camera links and refresh the page, then it shows the cameras. This wouldn't be so bad but it doesn't remember them if the browser is closed. Am I doing something wrong in the links? i.e.
<td><a href="http://192.168.1.85/img/video.mjpeg" target="_blank"><img src="http://192.168.1.85/img/video.mjpeg" width="400" height="300" ALT="OverheadDoor"></a></td>

Please advise. Thank you !

**Comment by krtek4** [comment]
Hi,

Sorry, but no, this is a limitation imposed by the browser.

The only way to avoid the issue would be to host the camera images on the same domain than the website itself.

Good luck !
