### ISSUE TITLE
Unable to access "chrome-extension://enhldmjbphoeibbpdhmjkchohnidgnah/popin.html" in Incognito mode

### ISSUE THREAD

**Issue by aks0109** [krtek4/MultiPass#71]
While accessing "chrome-extension://enhldmjbphoeibbpdhmjkchohnidgnah/popin.html" in incognito mode it's giving the below error, however it works fine in the regular mode.

enhldmjbphoeibbpdhmjkchohnidgnah is blockedRequests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

Any Idea how I can resolve this?

**Comment by krtek4** [comment]
Yes, you can disable the extension that is blocking access to MultiPass.

Sadly the error message doesn't give more information.

I'd check extensions such as AdBlock, uMatrix or any Privacy / Security related extensions.

Best,

**Comment by aks0109** [comment]
I am not using any other extension. Only extension used is Multipass. However I am connected to vpn.
