### ISSUE TITLE
Typing in a new entry in OSX does not show anything

### ISSUE THREAD

**Issue by jondoe1337** [krtek4/MultiPass#72]
When adding a new entry and typing in the needed fields, nothing is shown in the fields until you tab or switch into the next field.

Using Chrome Version 84.0.4147.125 (Official Build) (64-bit) with OSX 10.15.6 (Catalina).

**Comment by krtek4** [comment]
Hi,

This seems to be an issue with either OSX / Chrome than with the extension
itself.

We are using plain HTML inputs and this part wasn't changed in a long time.

Is it the only extension / web page where you encounter issues ?

**Comment by jondoe1337** [comment]
Yes.

Maybe you're right - could be OSX/Chrome related.
